# Generated by Django 5.1.3 on 2024-12-04 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the amenity', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the amenity', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location', max_length=255)),
                ('country', models.CharField(help_text='Country where the location is', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the location', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resort', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resort', null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night in USD', max_digits=10)),
                ('contact_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Image of the resort', null=True, upload_to='resorts/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the resort was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the resort was last updated')),
                ('amenities', models.ManyToManyField(blank=True, help_text='Amenities available at the resort', related_name='resorts', to='app.amenity')),
                ('location', models.ForeignKey(help_text='Location of the resort', on_delete=django.db.models.deletion.CASCADE, related_name='resorts', to='app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text="User's comment or feedback")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the comment was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the resort was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resort', models.ForeignKey(help_text='Resort this message is related to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.resort')),
            ],
        ),
    ]
