# Generated by Django 5.1.3 on 2024-12-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_resort_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='amenities',
        ),
    ]
