# Generated by Django 5.1.3 on 2024-12-05 02:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resort_options_remove_amenity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='amenities',
            field=models.TextField(blank=True, null=True, verbose_name=app.models.Amenity),
        ),
    ]
