# Generated by Django 5.1.4 on 2025-01-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_resort_resort_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_image',
            field=models.ImageField(default='static/images/paradise.jpg', help_text='Image of the resort', null=True, upload_to=''),
        ),
    ]
