# Generated by Django 5.1.3 on 2024-12-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resort_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='amenities',
        ),
    ]
