# Generated by Django 5.1.3 on 2024-12-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_resort_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Amenities available at the resort', related_name='resorts', to='app.amenity'),
        ),
    ]
