# Generated by Django 5.1.3 on 2024-12-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resort_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='location',
        ),
        migrations.AddField(
            model_name='resort',
            name='location',
            field=models.ManyToManyField(help_text='Location of the resort', related_name='resorts', to='app.location'),
        ),
    ]
