# Generated by Django 5.1.4 on 2025-01-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_resort_resort_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar-default.svg', null=True, upload_to=''),
        ),
    ]
