# Generated by Django 5.1.3 on 2024-12-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_resort_location_resort_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='Location of the resort', related_name='resorts', to='app.location'),
        ),
    ]
