# Generated by Django 5.1.3 on 2024-12-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_resort_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
    ]
