# Generated by Django 5.1.4 on 2025-01-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_resort_resort_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/avatar-default.svg', null=True, upload_to=''),
        ),
    ]
