# Generated by Django 5.1.3 on 2024-12-07 10:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='cottage',
            field=models.CharField(default='Default Cottage Name', max_length=100),
        ),
        migrations.AddField(
            model_name='resort',
            name='entrance_adults',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[app.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='resort',
            name='entrance_kids',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[app.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='resort',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resort',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
