# Generated by Django 5.1.4 on 2025-01-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_image',
            field=models.ImageField(blank=True, default='media/resorts/paradise.jpg', help_text='Image of the resort', upload_to='resorts/'),
        ),
    ]
