# Generated by Django 5.1.3 on 2024-12-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_resort_cottage_resort_entrance_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.TextField(blank=True, help_text="User's comment or feedback", null=True),
        ),
    ]
