# Generated by Django 5.1.4 on 2025-01-15 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_resorts', through='app.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
