# Generated by Django 5.1.4 on 2025-01-16 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_resort_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='app.resort'),
        ),
    ]
