# Generated by Django 5.1.4 on 2025-01-16 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_favorite_resort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='app.resort'),
        ),
    ]
