# Generated by Django 5.1.4 on 2025-01-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_favorite_resort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_resorts', to='app.resort'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'resort')},
        ),
    ]
