# Generated by Django 5.1.4 on 2025-01-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_favorite_resort_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='Average user rating of the resort'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.resort'),
        ),
    ]
