# Generated by Django 5.1.4 on 2025-02-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_resort_average_rating_alter_rating_resort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='resort',
            name='location_rating',
            field=models.FloatField(default=0.0, help_text="A score representing the resort's location"),
        ),
        migrations.AlterField(
            model_name='rating',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resort'),
        ),
    ]
