# Generated by Django 5.1.4 on 2025-03-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.resort'),
        ),
    ]
