# Generated by Django 5.1.4 on 2025-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_rating_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='mini_description',
            field=models.TextField(blank=True, help_text='Brief description of the resort', null=True),
        ),
    ]
