# Generated by Django 5.1.4 on 2025-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_resort_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='resort_image2',
            field=models.ImageField(blank=True, default='paradise.jpg', help_text='Image of the resort', upload_to='resorts/'),
        ),
    ]
