# Generated by Django 5.1.4 on 2025-03-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_resort_resort_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resort'),
        ),
    ]
