# Generated by Django 5.1.4 on 2025-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_rating_resort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='app.amenity'),
        ),
    ]
