# Generated by Django 5.1.4 on 2025-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_resort_resort_image2_resort_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='resorts/'),
        ),
    ]
