# Generated by Django 5.1.4 on 2025-03-31 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_resort_activities_image_resort_activity_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resorts/rooms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='app.resort')),
            ],
        ),
    ]
