# Generated by Django 5.1.4 on 2025-04-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_resortimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='activities_image',
            field=models.ImageField(blank=True, null=True, upload_to='resorts/'),
        ),
    ]
