# Generated by Django 5.1.4 on 2025-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_resort_activities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='activities_image',
            field=models.ImageField(blank=True, null=True, upload_to='resorts/activity/'),
        ),
    ]
