# Generated by Django 5.1.4 on 2025-04-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_resort_activities_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='activities_image',
            new_name='activity_image',
        ),
    ]
