# Generated by Django 5.1.4 on 2025-04-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_activities_image_resort_activity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='activity_image',
            new_name='activities_image',
        ),
    ]
