# Generated by Django 5.1.4 on 2025-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_resort_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
