# Generated by Django 5.1.4 on 2025-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_resort_latitude_resort_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
