# Generated by Django 5.1.4 on 2025-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_resort_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
