# Generated by Django 5.1.4 on 2025-04-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_resort_price_per_night'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResortImage',
            new_name='RoomImage',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='roomimage',
        ),
    ]
