# Generated by Django 5.1.4 on 2025-04-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_rename_resortimage_roomimage_remove_resort_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='beachimage',
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resorts/activities/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_images', to='app.resort')),
            ],
        ),
        migrations.CreateModel(
            name='BeachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resorts/beaches/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beach_images', to='app.resort')),
            ],
        ),
    ]
