# Generated by Django 5.1.4 on 2025-04-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_resort_beachimage_activityimage_beachimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='activities_image',
        ),
    ]
