# Generated by Django 5.1.4 on 2025-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_resort_activities_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_permit', models.ImageField(upload_to='subadmin_permits/')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
