# Generated by Django 5.1.4 on 2025-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminapplication',
            name='verification_permit',
            field=models.ImageField(upload_to='resorts/subadmin_permits/'),
        ),
    ]
