# Generated by Django 5.1.4 on 2025-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_subadminapplication_verification_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminapplication',
            name='verification_permit',
            field=models.ImageField(null=True, upload_to='resorts/subadmin_permits/'),
        ),
    ]
