# Generated by Django 5.1.4 on 2025-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_resort_cottage_cottage_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='resort',
        ),
        migrations.AddField(
            model_name='resort',
            name='cottage',
            field=models.CharField(default='Default Cottage Name', max_length=100),
        ),
        migrations.DeleteModel(
            name='Cottage',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
