# Generated by Django 5.1.4 on 2025-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_room_resort_resort_cottage_delete_cottage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='cottage_price_range',
            field=models.CharField(choices=[('low', 'Low'), ('average', 'Average'), ('high', 'High')], default='average', help_text='Select the price range for cottages', max_length=10),
        ),
        migrations.AddField(
            model_name='resort',
            name='room_price_range',
            field=models.CharField(choices=[('low', 'Low'), ('average', 'Average'), ('high', 'High')], default='average', help_text='Select the price range for rooms', max_length=10),
        ),
    ]
