# Generated by Django 5.1.4 on 2025-04-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_resort_cottage_price_range_resort_room_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='cottage',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='price_per_night',
        ),
    ]
