# Generated by Django 5.1.4 on 2025-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_resort_cottage_remove_resort_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='cottage_price_range',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='room_price_range',
        ),
        migrations.AddField(
            model_name='resort',
            name='cottage',
            field=models.CharField(default='Default Cottage Name', max_length=100),
        ),
        migrations.AddField(
            model_name='resort',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
