# Generated by Django 5.1.4 on 2025-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_remove_resort_cottage_price_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='activity_description',
            field=models.TextField(blank=True, help_text='Activity description', null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='beach_description',
            field=models.TextField(blank=True, help_text='Beach description', null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='mini_description',
            field=models.TextField(blank=True, help_text='Mini description of the resort', null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='room_description',
            field=models.TextField(blank=True, help_text='Room description', null=True),
        ),
    ]
