# Generated by Django 5.1.4 on 2025-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_resort_cottage_price_range_resort_room_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminapplication',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='subadminapplication',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the resort', null=True),
        ),
        migrations.AddField(
            model_name='subadminapplication',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the resort', max_length=200, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='subadminapplication',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='subadminapplication',
            name='resort_image',
            field=models.ImageField(blank=True, null=True, upload_to='resorts/images/'),
        ),
    ]
