# Generated by Django 5.1.4 on 2025-04-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_subadminapplication_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminapplication',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the resort', max_length=200, null=True, verbose_name='Location'),
        ),
    ]
