# Generated by Django 5.1.4 on 2025-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_subadminapplication_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
