# Generated by Django 5.1.4 on 2025-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_subadminapplication_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
