# Generated by Django 5.1.4 on 2025-05-09 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_resort_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resorts', to=settings.AUTH_USER_MODEL),
        ),
    ]
