# Generated by Django 5.1.4 on 2025-05-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_landmark_resort_landmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='landmark',
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
